### ISSUE TITLE
Hi I have loaded Phon 2.1 for an Academic, She started a session and linked one of the demo media fIles (Win7 networked PC) it will not play in the media player, however Speech Analysis sees the file and can play it, and I can openthe file with a stand aone media player on the PC.  I know nothing about this software, any help appreciated

### ISSUE THREAD

**Issue by YSJ-John** [phon-ca/phon#1]

**Comment by ghedlund** [comment]
Hey there, thanks for letting us know about the issue.

There are two things which may be happening:
 * If VLC is installed on the computer, it may be out of date.  Phon 2.1 requires VLC 2.1.0 or later.

 * Phon is unable to find the VLC plugins folder. This can be forced by setting the VLC_PLUGIN_PATH environment variable to the location of the VLC installation folder. This is usually `C:\Program Files\Videolan\VLC\plugins`

Anything you can tell us about the configuration of the computer would be helpful.  I've had a report about this issue occurring on 32-bit, Windows 7 computer in a lab setting - but I'm unsure as to why the issue exists as the plugins should be found if installed in the default location.

Cheers,

-Greg

**Comment by YSJ-John** [comment]
Hi Greg

Thanks for reply, this is a 32bit win 7 Lab at York St John.  We are using VLC 2.1.3 so that’s eliminated. I have also installed on my PC as a test.

I will speak to our tech experts ref setting the VLC_PLUGIN_PATH environment variable and let you know the result.

Regards

John Kemsley
ILS



John Kemsley
Network Assistant
Information Learning Services
York St John University
YO31 7EX

T: +44 (0) 1904 876696
E: j.kemsley@yorksj.ac.uk<mailto:j.kemsley@yorksj.ac.uk>



[cid:image001.png@01D11235.BA2B6DB0]Open Access – REF2020

From April 2016, to be eligible for submission to REF2020, all research outputs must have been deposited in RaY<http://ray.yorksj.ac.uk/> within 3 months of acceptance.
For further information on Open Access, please see our Open Access policy<http://www.yorksj.ac.uk/information-learning-services/information-learning-services/services-for-you/staff/teaching--learning-repository/open-access-policy.aspx>, web page<http://www.yorksj.ac.uk/information-learning-services/information-learning-services/services-for-you/researcher-and-postgraduate/open-access.aspx>, or contact your Academic Liaison Librarian<http://www.yorksj.ac.uk/information-learning-services/information-learning-services/services-for-you/staff/academic-liaison.aspx>.

**Comment by ghedlund** [comment]
Hello John,

This issue has been fixed in version 2.1.8.

Thanks again for bringing this issue to our attention!

Cheers,

-Greg

**Comment by YSJ-John** [comment]
Hi Greg

Tested update and it works on my PC

Thanks!!

John


John Kemsley
Network Assistant
Information Learning Services
York St John University
YO31 7EX

T: +44 (0) 1904 876696
E: j.kemsley@yorksj.ac.uk<mailto:j.kemsley@yorksj.ac.uk>



[cid:image001.png@01D11235.BA2B6DB0]Open Access – REF2020

From April 2016, to be eligible for submission to REF2020, all research outputs must have been deposited in RaY<http://ray.yorksj.ac.uk/> within 3 months of acceptance.
For further information on Open Access, please see our Open Access policy<http://www.yorksj.ac.uk/information-learning-services/information-learning-services/services-for-you/staff/teaching--learning-repository/open-access-policy.aspx>, web page<http://www.yorksj.ac.uk/information-learning-services/information-learning-services/services-for-you/researcher-and-postgraduate/open-access.aspx>, or contact your Academic Liaison Librarian<http://www.yorksj.ac.uk/information-learning-services/information-learning-services/services-for-you/staff/academic-liaison.aspx>.
