### ISSUE TITLE
Media not playing from Speech Analysis window

### ISSUE THREAD

**Issue by AlexCucinelli** [phon-ca/phon#10]
In Phon 3.0.0b1, once the media file is linked in Session Information the file will play from the Media Player window but not from the Speech Analysis window. This was tested on three different computers, including that of @yrose.

**Comment by ghedlund** [comment]
Phon is not selecting the correct output device in the Speech Analysis view.

You can select the correct device by right-clicking the speech analysis view and choosing the correct output device from the 'Output device' menu.

**Comment by ghedlund** [comment]
Fix in e5be7036b1883e5b92d67410b99b2622c44d707c
