### ISSUE TITLE
Set volume of Media Player and all other audio playback system in Phon to 100% by default

### ISSUE THREAD

**Issue by yrose** [phon-ca/phon#100]
Related note: At least one Windows user cannot use the volume cursor in Media Player. No errors appear in the log but the cursor is greyed-out in his interface and so he can't move it up or down.

**Comment by ghedlund** [comment]
Audio levels are at 100% by default - audio levels in VLC are shown up to 200%.

**Comment by ghedlund** [comment]
> Related note: At least one Windows user cannot use the volume cursor in Media Player. No errors appear in the log but the cursor is greyed-out in his interface and so he can't move it up or down.

This would happen if: no media is available or VLC has not been loaded.  This should be a separate issue and review of logs would be necessary.
