### ISSUE TITLE
Add Ignore Diacritics Setting to Analysis Table Nodes

### ISSUE THREAD

**Issue by yrose** [phon-ca/phon#101]
As per the title

**Comment by ghedlund** [comment]
This is much more complicated than it would seem. Ignore diacritics is a setting which appears on our inventory nodes. The settings for internal analysis nodes may not be available but the global ignore diacritics settings will have an effect. The effect of this setting should be defined for each individual analysis and is not generalize-able due to the number of individual processing nodes which may exist in the analysis document.

**Comment by ghedlund** [comment]
Also - I expect what you really want here is a new setting on the table report nodes which will 'strip diacritics' from specified IPA columns.

**Comment by yrose** [comment]
Yes. Something we'll need to discuss. And I'm sure it won't be possible for all analyses.


On Jul 28, 2020, at 2:20 PM, Gregory Hedlund <notifications@github.com<mailto:notifications@github.com>> wrote:



Also - I expect what you really want here is a new setting on the table report nodes which will 'strip diacritics' from specified IPA columns.

**Comment by ghedlund** [comment]
I think we will cover all our bases by adding the diacritic options to the
query results to table node. It will have to apply to all columns as I will
need to remove the diacritics from alignment data if the analysis - such as
ppc and patch - requires it. All query data goes into this node for reports
and analyses so any operations after this node will work with stripped
versions of the transcript.

**Comment by yrose** [comment]
This sounds perfectly logical, as query result sorts will unavoidably be affected by options with the diacritics.



On Jul 28, 2020, at 3:04 PM, Gregory Hedlund <notifications@github.com<mailto:notifications@github.com>> wrote:


I think we will cover all our bases by adding the diacritic options to the
query results to table node. It will have to apply to all columns as I will
need to remove the diacritics from alignment data if the analysis - such as
ppc and patch - requires it. All query data goes into this node for reports
and analyses so any operations after this node will work with stripped
versions of the transcript.

**Comment by ghedlund** [comment]
Diacritic options have been added to the 'Results to Table' node. They can be set using the global overrides, input fields, or settings panel. Diacritics will be remove from both IPA and text based result values.
