### ISSUE TITLE
PPC-r

### ISSUE THREAD

**Issue by yrose** [phon-ca/phon#103]
Add option to PPC so that all phones with the 'distorted' diacritic (33E) are computed as 'accurate' (instead of substituted).

**Comment by ghedlund** [comment]
The ability to set this up already exists with current PCC options.  I'll add a new flag/button above the 'ignore diacritics' so that the ignore diacritics options are setup correctly when clicked but it may be difficult to update checkbox status correctly due to the dynamic nature of these forms.

**Comment by ghedlund** [comment]
Current impl using ignore diacritics settings will not mark distorted phones as correct.
