### ISSUE TITLE
Add options to Consonants analysis

### ISSUE THREAD

**Issue by yrose** [phon-ca/phon#104]
Additional options:

Word-initial Singleton Onsets
Word-final Singleton Codas
Word-initial Clusters (including appendices)
Word-final Clusters (including appendices)

**Comment by ghedlund** [comment]
This will require a re-think of the form as the options are currently covering the whole set of possible cluster types - including those listed above.

**Comment by ghedlund** [comment]
Maybe add descriptive text as another column? Something like 'word position' with values: initial, medial, final?

**Comment by yrose** [comment]
Yes this would be a good approach, intuitive to the user as well.

**Comment by ghedlund** [comment]
I think the best path forward would be to add positional information to the query results. This will result in the following new columns in report tables:

 * Position - either group or word position depending on domain set in query (Initial, Medial, or Final)
 * Syllable position - include if 'then by syllable' is selected (Initial, Medial, or Final)

Position will be based on the first result value (IPA Target in aligned results or IPA Actual if the query is reversed.) I'm wondering if there should also be an 'Aligned position' for aligned results?

**Comment by yrose** [comment]
I think the best path forward would be to add positional information to the query results. This will result in the following new columns in report tables:

  *   Position - either group or word position depending on domain set in query (Initial, Medial, or Final)
  *   Syllable position - include if 'then by syllable' is selected (Initial, Medial, or Final)

This would work perfectly fine as people can then filter out the results they are not interested in.


Position will be based on the first result value (IPA Target in aligned results or IPA Actual if the query is reversed.) I'm wondering if there should also be an 'Aligned position' for aligned results?

Good thinking! If it weren't too hard to put that in, would be excellent.

**Comment by ghedlund** [comment]
I'll add this as a new option 'Include positional information with result' and it will appear under the 'Search by' options.

**Comment by yrose** [comment]
Sounds perfect.

On Sep 2, 2020, at 11:44 AM, Gregory Hedlund <notifications@github.com<mailto:notifications@github.com>> wrote:



I'll add this as a new option 'Include positional information with result' and it will appear under the 'Search by' options.
