### ISSUE TITLE
Percentage Singletons Consonants Correct >> Singleton Codas does not pick up codas in IPA Target forms

### ISSUE THREAD

**Issue by yrose** [phon-ca/phon#108]
Data attached.  All scores turn to 0 because no coda detected in IPA Target forms. 

[T1.txt](https://github.com/phon-ca/phon/files/5197028/T1.txt)

**Comment by ghedlund** [comment]
The codas in this example is preceded by a consonant marked as a vowel.

**Comment by yrose** [comment]
Yes, where the glide in this example (da**w**n) is the 2nd half of a falling diphthong, followed by a singleton coda. Your comment suggests that the phonex doesn’t make proper reference to syllable structure, although it's hard for me to judge without seeing the expression.

**Comment by ghedlund** [comment]
You can view the phonex by selecting the option and then selection '(custom)' to view the expression. Updated expressions for singleton onsets/codas have already been added to the list of built-in Phones queries but they were not updated in the PPC library.

Note: if you select 'Tautosyllabic clusters' the 'wn' sequence will be returned.
