### ISSUE TITLE
Project level check sessions

### ISSUE THREAD

**Issue by AlexCucinelli** [phon-ca/phon#12]
Overlapping segment times are flagged as an error within each Phon session. Is it possible to have this function incorporated into the project level Check Transcriptions function? 

----

Todo:

 * [x] Create a new 'Check Sessions' wizard
    - Options should include reset syllabification + reset alignment.
 * [x] Use 'Quick Fix' api to attempt repairs where possible (optional)
 * [x] Replace existing 'Check Transcriptions' wizard with new 'Check Sessions' wizard and update project menu.

**Comment by yrose** [comment]
* Put something else that "Errors" in the bar when the process is ongoing. It gives the impression something wrong's happening. 

* During the process, provide some feedback as to what session is being processed. Something like the 'flying stars' (LOL) used with the number of results listed within the Query/Analysis process would work perfectly. The number listed could be the # of records.
