### ISSUE TITLE
Inter-transcriber reliability and PPC reports: Include all the diacritics (and tones) in all results

### ISSUE THREAD

**Issue by yrose** [phon-ca/phon#121]
Even when ignore diacritics/tonal numbers is selected for the analyses, the forms returned in the results table should ideally contain this information (i.e. the full transcription)

This applies to both ITR and all PPC reports. 

<img width="739" alt="ExampleYouran" src="https://user-images.githubusercontent.com/15111886/101173624-5b618000-361d-11eb-8cb2-db8c4f13b28b.png">

**Comment by ghedlund** [comment]
This is not possible because the information does not exist in the transcriptions when the analysis is performed when ignore diacritics is selected.

-Greg
