### ISSUE TITLE
Function/method to change project names after they were created

### ISSUE THREAD

**Issue by yrose** [phon-ca/phon#122]
With the removal of the project.xml file, how can we change this information? 

More generally, I am not sure whether hidden files are the way to go to store this information. It creates confusion when we share projects between platforms. A possibility would be an explicit "_project description" file alongside the corpus folders -- but in a way that would avoid previous issues with the project.xml file

**Comment by ghedlund** [comment]
1) Hidden files - all platforms support hidden files and if you copy folders the files will be included.  The property files should not, however, be added to version control and that is our default behavior.

2) The project name was moved into the .properties file because I was deprecating the method of storing the project name. I was moving to make 'project name' irrelevant and simple use the current project folder name.

**Comment by yrose** [comment]
1. I have seen a lot of pesky .files originating from macOS into Windows repositories. I never saw the reverse on my system. I can't recall if .properties was one of them, though (so I'm not sure at the moment). 
2. I would be OK with using project folder name for project name. And I'm completely OK with the current _description files. I would like it if we could eliminate .properties so all our file system is simple and fully visible, as long as this doesn't create problems I can't expect from my end of things.

**Comment by ghedlund** [comment]
On 1/12/2021 9:57 AM, yrose wrote:
>
>  1. I have seen a lot of pesky .files originating from macOS into
>     Windows repositories. I never saw the reverse on my system. I
>     can't recall if .properties was one of them, though (so I'm not
>     sure at the moment).
>
I'm not sure to what you might be referring to other than the .MS_Store 
files, but in general it shouldn't be an issue.  The .properties file 
stores some application-level information such as the media folder 
information for projects/corpora and I'm expecting it to eventually 
store other project-level and plug-in options. The data stored in this 
file can be shared between users, but shouldn't be published.

>  1. I would be OK with using project folder name for project name. And
>     I'm completely OK with the current _description files. I would
>     like it if we could eliminate .properties so all our file system
>     is simple and fully visible, as long as this doesn't create
>     problems I can't expect from my end of things.
>
Project name is only use in UI elements as far as I can tell, it has no 
real importance to anything on the data side of things. Using folder 
name keeps things simple and easy to modify.  I will make this change 
when I get the folder watcher setup on the project folder.

**Comment by yrose** [comment]
OKdoke. Next time I run into the hidden file issue on Windows I'll make sure to better document everything.

On Jan 12, 2021, at 10:08 AM, Gregory Hedlund <notifications@github.com<mailto:notifications@github.com>> wrote:



On 1/12/2021 9:57 AM, yrose wrote:
>
> 1. I have seen a lot of pesky .files originating from macOS into
> Windows repositories. I never saw the reverse on my system. I
> can't recall if .properties was one of them, though (so I'm not
> sure at the moment).
>
I'm not sure to what you might be referring to other than the .MS_Store
files, but in general it shouldn't be an issue.  The .properties file
stores some application-level information such as the media folder
information for projects/corpora and I'm expecting it to eventually
store other project-level and plug-in options. The data stored in this
file can be shared between users, but shouldn't be published.

> 1. I would be OK with using project folder name for project name. And
> I'm completely OK with the current _description files. I would
> like it if we could eliminate .properties so all our file system
> is simple and fully visible, as long as this doesn't create
> problems I can't expect from my end of things.
>
Project name is only use in UI elements as far as I can tell, it has no
real importance to anything on the data side of things. Using folder
name keeps things simple and easy to modify.  I will make this change
when I get the folder watcher setup on the project folder.

**Comment by ghedlund** [comment]
bump
