### ISSUE TITLE
Tier management: Delete record data when deleting tiers

### ISSUE THREAD

**Issue by yrose** [phon-ca/phon#124]
Currently Phon doesn't delete the tier data when we delete a tier in Tier management. A few more notes (building on our phone call): 
 - this action doesn't need to be undoable -- as long as we impose a clear warning, where cancel is set as the default button
 - re: managing what's in memory, etc., an option could be to move this action outside of the Session Editor, or force some save/reload of the session transcript, whatever makes things easier

**Comment by ghedlund** [comment]
Looked at the code - record data should be deleted and is undo-able.
Everything looked good when I checked.
