### ISSUE TITLE
Function or script to add/remove values (in ms) for segment times

### ISSUE THREAD

**Issue by yrose** [phon-ca/phon#125]
Key to this request is the ability to add or subtract a user-specified amount of time to all segments within a given session. For example: "add 002:33.354 to all segment times in Session X"

This could be barebones using a script, or a function built into the session menu of Session Editor or Project menu of Project Manager. Whatever works best for you/ Phon.

I would be OK using milliseconds as units, but would very much like the ability to enter the values as MMM:SS.MMM, the way they are displayed in Session Editor. Having both would avoid the need for doing conversions using 3rd party software. If I have to choose between the two options, MMM:SS.MMM please.

**Comment by ghedlund** [comment]
This sounds like a new action inside the Timeline view. As such, the option to choose to do this by participant should also be available.

**Comment by yrose** [comment]
Because of the one-one association between transcripts and records, it seems to me that if we need to move records for any participant, all of the others should move too. 

To put this in Timeline is an excellent idea because we'll be able to fine-tune the work based on the timeline's GUI.

**Comment by ghedlund** [comment]
Moving to a new ticket
