### ISSUE TITLE
Removing session date in Session Information does not remove it from the file

### ISSUE THREAD

**Issue by yrose** [phon-ca/phon#126]
Steps:
Open session
Go to Session Information
Remove session date
     - Phon does not record the change
Do something else in interface so a change gets recorded (e.g. change media filename)
Save and close
    - Date still there when you reopen session
 
[010700.txt](https://github.com/phon-ca/phon/files/5810579/010700.txt)

**Comment by ghedlund** [comment]
Session date is a required item and can't be removed.  If date needs to be anonymized then choose either a random date or set to something like '1-JAN-1970'

**Comment by ghedlund** [comment]
Session date will now reset inside field if session date is empty on focus change.
