### ISSUE TITLE
OpGraph error when working with syllabifier files

### ISSUE THREAD

**Issue by yrose** [phon-ca/phon#135]
Open Phon
Composer (advanced)
Open syllabifier file (attached)
Run the debug steps (e.g. Step to Next button) using the IPA word ˌɹikn̩ˈstɹʌkʃn̩z
> Error occurs (log attached)

[OpGraph.zip](https://github.com/phon-ca/phon/files/5897010/OpGraph.zip)

**Comment by ghedlund** [comment]
Fixed in 3.2.1-beta.4
