### ISSUE TITLE
Updated eng dictionary based on file attached 

### ISSUE THREAD

**Issue by yrose** [phon-ca/phon#136]
File is missing the headers required in the eng.map file. (I destroyed the original you sent me by mistake.) 

This file replaces the English dictionary, but not the UK or the Legacy ones. 

[eng.txt](https://github.com/phon-ca/phon/files/5911275/eng.txt)

**Comment by yrose** [comment]
Final file attached. Still missing the headers required in the eng.map file.

This file replaces the English dictionary, but not the UK or the Legacy ones.

[eng.txt](https://github.com/phon-ca/phon/files/5934683/eng.txt)

**Comment by ghedlund** [comment]
1) There is no eng.map file - '.map' is for transliteration dictionaries
2) The prefix is in a separate file and gets added during compilation
