### ISSUE TITLE
Word match analysis

### ISSUE THREAD

**Issue by yrose** [phon-ca/phon#142]
A few issues with the Word match analysis

1) CV match/mismatch analyses must not worry about segmental contents; so as long as Actual Vs and Cs are matched with Target Vs and Cs, even if these latter ones are different from the former, they should be matches. Only the parameters for the CV match should apply, irrespective of the Exact Match diacritic options.

2) Ideally, the Exact match diacritic options should be the same as in the PPC, etc. 

3) In the current version of Phon (3.2.1-beta.5), the Analysis Composer does not display the parameters options for the Word match.

**Comment by yrose** [comment]
Attached is an example file, where the 7 words in the sample should return a perfect CV match. 


[7 words.txt](https://github.com/phon-ca/phon/files/6005060/7.words.txt)

**Comment by ghedlund** [comment]
Due to neglect this analysis is fairly broken and will need a re-write to be of use in the future. Honestly I've forgotten what it was even designed to do and there was never any documentation written.

**Comment by yrose** [comment]
I can work with you. Let's make this a priority.

**Comment by yrose** [comment]
Attached is a description in LO of the analysis. I see one change in the processing of CV match that's different from the original. Let's discuss this when you get to this work.

[Word Match - description.odt.zip](https://github.com/phon-ca/phon/files/6063774/Word.Match.-.description.odt.zip)

**Comment by ghedlund** [comment]
From the description I have identified four smaller analyses:

 1) "Tier Match" - given two tiers provide the following information (group/word level options available)     
  • Word Count: number of words included in the analysis
  • # Exact Match: number of words produced as exact matches to the target
  • # Exact Mismatch: number of words produced which differ from the target by at least one property
  • % Exact Match: # Exact Match ÷ Word Count * 100

 2) "CV Pattern"     
  • # CV Match: Target/actual word pairs which present identical CV structures (irrespective of segmental melodies, or diacritics unless specified, such as length or nasalization on vowels where following nasal consonants are deleted)
  • # CV Mismatch: Target/actual word pairs which do not present identical CV structures
  • % CV Match: # CV Match ÷ Word Count * 100

 3) "Syllable Count"
  • # Syllable Count Match: Target/actual word pairs with the name number of syllables
  • # Syllable Count Mismatch: Target/actual word pairs with different numbers of syllables
  • % Syllable Count Match: # Syllable Count Match ÷ Word Count * 100

 4) "Stress Pattern"
  • # Stress Match: Target/actual word pairs with identical stress patterns
  • # Stress Mismatch: Target/actual word pairs with different stress patterns
  • % Stress Match: # Stress Match ÷ Word Count * 100

In addition to the requested information each analysis will contain an inventory of relevant 'patterns' similar to the 'IPA Patterrns' table which appears in other analyses.

These 4 analyses will become available first, then I will tackle the task of combining them using *linked* versions of the above analyses.
