### ISSUE TITLE
Check session > segment time overlaps not reported in 3.3.0-beta.1

### ISSUE THREAD

**Issue by yrose** [phon-ca/phon#144]
Attached is a session file and a screen shot showing the overlaps in records 43ff. 

These overlaps are not reported by session check. 

[Overlaps.zip](https://github.com/phon-ca/phon/files/6054875/Overlaps.zip)

**Comment by ghedlund** [comment]
These overlaps are set to be within the threshold of this function.

**Comment by yrose** [comment]
This implies that the overlaps are under-reported and end up being problems for data roundtrips, TextGrid generation, etc.. Why do we need a threshold? Can we not flag all overlaps in session checks?

**Comment by ghedlund** [comment]
I don't mind setting the overlap threshold to zero - this was always a request from you. The segment overlap are detected differently between the two functions. Timeline uses a 2D coord system to detect overlaps in rectangles, while the session check sides uses a iterative method.

**Comment by yrose** [comment]
Yes, let's bring it down to zero, please.
