### ISSUE TITLE
CHAT files fail to import into Phon

### ISSUE THREAD

**Issue by yrose** [phon-ca/phon#152]
These 3 files were generated by Phon and pass the Chatter conversion. However, they fail to import into a Phon project. 

[ImportIssues.zip](https://github.com/phon-ca/phon/files/6143429/ImportIssues.zip)

**Comment by ghedlund** [comment]
chatter is placing a '<ca-element type='primary-stress'/>' where stress markers appear in the main line, we do not support ca-elements yet.

e.g.,
<pg><w>apa<ca-element type="primary stress"/>gow</w><actual>

**Comment by yrose** [comment]
Easy to fix, but hard to find without cues - but would there be a way to message this when we run the conversions?

On Mar 18, 2021, at 2:41 AM, Gregory Hedlund ***@***.******@***.***>> wrote:



chatter is placing a '' where stress markers appear in the main line, we do not support ca-elements yet.

e.g.,
apagow
