### ISSUE TITLE
Comment in file headers prevent export

### ISSUE THREAD

**Issue by yrose** [phon-ca/phon#154]
Attached are Phon files. Exporting them to CHAT seems to be blocked by the comments that appear in the headers of the original CHAT files. 

- Open corpus in Phon
- Export to CHAT

[Jacob.zip](https://github.com/phon-ca/phon/files/6148953/Jacob.zip)

**Comment by ghedlund** [comment]
The comment type 'TapeLocation' must have been removed from the CHAT specification. The comments need to be removed manually from the xml.

E.g.,: 
<comment type="TapeLocation">tape 3, side 1, channel 1. Original tape speed 3.75 feet per second.</comment>

You can also change the 'type' attribute to 'Generic' to save this information.

E.g.,
<comment type="Generic">tape 3, side 1, channel 1. Original tape speed 3.75 feet per second.</comment>

**Comment by yrose** [comment]
OK that works. Thank you.

On Mar 16, 2021, at 11:01 AM, Gregory Hedlund ***@***.******@***.***>> wrote:



The comment type 'TapeLocation' must have been removed from the CHAT specification. The comments need to be removed manually from the xml.

E.g.,:
<comment type="TapeLocation">tape 3, side 1, channel 1. Original tape speed 3.75 feet per second.</comment>

You can also change the 'type' attribute to 'Generic' to save this information.

E.g.,
<comment type="Generic">tape 3, side 1, channel 1. Original tape speed 3.75 feet per second.</comment>
