### ISSUE TITLE
Ewe transliteration - issue with default low tone insertion

### ISSUE THREAD

**Issue by yrose** [phon-ca/phon#16]
1) Low tones appear unexpectedly on a number of phone. For example, if you type m by itself (i.e. without a tonal marker H or L), it comes with a low tone within the transliterated form (e.g. oman > [òm̀àn]). So it seems like the rule to insert low tones automatically (which is otherwise very useful) is overapplying. 

2) There also seems to be some unwanted interaction between this rule and vowels transcribed with nasal tildes (e.g. e\~lan > [è~làn] instead of [ẽ̀làn])

**Comment by yrose** [comment]
Further note: There are no rules there within the translit system I don't think, but maybe something about the order of the replacements within the translit list that gives the impression there is a rule.

**Comment by yrose** [comment]
I worked with Gladstone directly on this. The attached file contains supersedes what's in Phon 3.0.0.

In this new translit system, we are using ' (apostrophe/single quotation mark) to map the the nasal tilde. I hope this won't clash with anything in the Session Editor.

[EweTranslit.txt](https://github.com/phon-ca/phon/files/2421844/EweTranslit.txt)

**Comment by yrose** [comment]
Translit scheme completely revised. 

[EweTranslit-withHeadings-revd3.txt](https://github.com/phon-ca/phon/files/2440175/EweTranslit-withHeadings-revd3.txt)

**Comment by yrose** [comment]
Translit scheme completely revised.

[EweTranslit-withHeadings-revd4.txt](https://github.com/phon-ca/phon/files/2442099/EweTranslit-withHeadings-revd4.txt)

**Comment by ghedlund** [comment]
Version include name, language and post find/replace rules.

[ewe.txt](https://github.com/phon-ca/phon/files/2461618/ewe.txt)

**Comment by yrose** [comment]
The new translit works well generally, but still needs minor adjustments, as follows:

 1. /ɔ, ɛ/ which were O and E in orthography are no longer in the system or the orthography has changed and I do not know what they are now. 

Solution: add the following correspondences:
O > ɔ
E > ɛ

 2. MH and HM contour tones are do not come as contours but multiple tones on the vowel.

Solution: add the following correspondences:
MH >  ᷄ (1DC4)
HM > ᷅ (1DC5)

Attached is the revised scheme containing these changes.

[ewe.txt](https://github.com/phon-ca/phon/files/2482802/ewe.txt)

**Comment by ghedlund** [comment]
Updated in 3.0.2b1
