### ISSUE TITLE
Memory issue with Phone Inventory analysis

### ISSUE THREAD

**Issue by yrose** [phon-ca/phon#161]
In its current implementation, the Phone Inventory analysis tends to run out of memory with only a few session transcripts. I'm not sure how much could be done on the computational side of things, but I also find the report to contain perhaps too many sections with little purposes. Best would probably to discuss this before making any move.

**Comment by ghedlund** [comment]
There are improvements that can be made to how memory is managed internally during opgraph execution. Things are setup for debugging purposes at the moment - which basically instructs each node in the graph to keep it's local context in memory forever.

The dataset I use for 'large' corpus tests is usually the Catootje corpus. This seems to pass ok, so an example dataset would be good here.
