### ISSUE TITLE
Errors on report generation - source of error hard to find

### ISSUE THREAD

**Issue by yrose** [phon-ca/phon#164]
Please find attached a full project, including a query and a report (aggregate). 

All the session have been checked using Session Check. Other than a few segment overlaps, there are no warnings generated by Phon.

Two issues:
1) If I run the included query on the 5 sessions from 040418 to 040618 together, then report fails. However, I can do the fully query and reporting on each of these 5 sessions.

2) Individually, the following files fail to generate a report:
	040829
	050411
	050509
	050606
	051026

I looked at some of the data the best I could but didn't identify an obvious problem. Thank you for your help dealing with this, if only to identify what the problem may be.

[Reporting errors.zip](https://github.com/phon-ca/phon/files/6600176/Reporting.errors.zip)

**Comment by ghedlund** [comment]
An issue with alignment with the Morphology tier highlighting the need for #91
