### ISSUE TITLE
Modify IPA parser so that length diacriitcs come after suffix diacriitcs

### ISSUE THREAD

**Issue by yrose** [phon-ca/phon#165]
As per the screen shot: it seems like long aspirated Cs are not supported in Phon. Yet they are logical phones, well attested across languages. For example: if [tːa] is supported, then so should [tʰːa] or any other consonant with a contour diacritic.

![Screen Shot 2021-06-04 at 2 14 59 PM](https://user-images.githubusercontent.com/15111886/120839033-09a1a000-c543-11eb-800a-3f3eabd047c7.png)

**Comment by ghedlund** [comment]
Length must come before suffix diacritics

**Comment by yrose** [comment]
This is interesting because no one would ever think of typing a long consonant with contour without placing the length diacritic at the end. So while [tʰːa] is logical, [tːʰa] is not. This is an issue we'll have to address at some point in the future (no rush, but important).

**Comment by ghedlund** [comment]
I can swap the ordering of length and suffix diacritics - but this may cause issues for older data. They cannot be mixed.

**Comment by yrose** [comment]
This would be OK. As long as the reversed order is picked up by Session Check we'll be all good to go. As a general rule of thumb, length should always be the last element of a transcribed phone (by convention in phonology)

**Comment by ghedlund** [comment]
What about tone number?

**Comment by yrose** [comment]
Tone numbers should come at the very end, after the length mark(s). Tone diacritics should come before, along with other combining diacritics.

Sent from my iPhone

On Jun 7, 2021, at 6:10 AM, Gregory Hedlund ***@***.***> wrote:

﻿

What about tone number?
