### ISSUE TITLE
Need help with this issue

### ISSUE THREAD

**Issue by yrose** [phon-ca/phon#169]
Attached are 5 sessions and a query. 

If you run the query on each individual session and report an aggregate for them, everything work. 
If you run the query on ALL of these 5 sessions at once and report an aggregate, then an error gets generated. 

We fixed all these sessions for word alignment so it doesn't seem like this is where the problem is, unless there's something else that doesn't get reported in Check Sessions. 

Thank you for your help! Please let me know if you have questions about replicating this issue.

[Archive.zip](https://github.com/phon-ca/phon/files/6672036/Archive.zip)

**Comment by yrose** [comment]
Adding this to the ticket -- custom aggregate that yields the issue

[AggregateYvan.xml.zip](https://github.com/phon-ca/phon/files/6672206/AggregateYvan.xml.zip)

**Comment by ghedlund** [comment]
The 'keep like on top' option causes the error in the sort algorithm.  This option will need to be implemented using a different approach.

**Comment by yrose** [comment]
Yet the option works if the IPA tiers aren't specified in column sorting. If you keep all options to default except Keep on Top then there's no error
