### ISSUE TITLE
Interaction between *action* and final punctuation in word alignment?

### ISSUE THREAD

**Issue by yrose** [phon-ca/phon#170]
The attached screenshot shows a record that gets flagged with Word Alignment checks. What may be going on is the extra space between the *laugh* annotation and the final punctuation. 

![Screen Shot 2021-06-17 at 2 34 23 PM](https://user-images.githubusercontent.com/15111886/122475255-f65cee80-cf9e-11eb-9a59-0d46b8fa3050.png)

**Comment by ghedlund** [comment]
This is actually because the '.' is not part of word alignment, but you have it as part of the Morphology tier (which is correct for CHAT.) This will always get flagged as a warning in Phon because we do not have special rules for user defined tiers.
