### ISSUE TITLE
Issue with Table Options in Listing and Listing by Session

### ISSUE THREAD

**Issue by yrose** [phon-ca/phon#18]
See attached screen shot. Affects both listing layouts. Data and query method also attached.

[Data&Query.zip](https://github.com/phon-ca/phon/files/2385210/Data.Query.zip)

<img width="972" alt="bug report" src="https://user-images.githubusercontent.com/15111886/45580330-80b21a00-b86a-11e8-8081-267cc72a6f02.png">

**Comment by ghedlund** [comment]
See https://github.com/phon-ca/phon/issues/19

**Comment by ghedlund** [comment]
The above formatting is actually correct.  The options as they have been selected say *only include* the listed columns.  You should keep the original settings of 'Exclude columns' in the Listing settings.
