### ISSUE TITLE
Add volume control to Segment Playback

### ISSUE THREAD

**Issue by yrose** [phon-ca/phon#187]
This is an oft-requested feature. There is also the problem that if we turn down the volume in Media Player (and even with Media Player not loaded in the interface), then playback in Timeline is muted.

**Comment by ghedlund** [comment]
When playing back a segment in can happen in two ways:
 1) Media is available but no session audio file is loaded in Timeline - segment is played in VLC and VLC volumn applies
 2) Media is available and session audio file is loaded in Timeline - segment audio is played directly to mixer using low level APIS, media is played in VLC without audio. Only system volume here affects audio playback, there is no way for me to programmatically alter volume using this API.

If anything, the solution here would be to remove volume control on VLC and have people only use their system audio controls (which is what you should do anyway.)
