### ISSUE TITLE
Updated Mandarin Chinese dictionary

### ISSUE THREAD

**Issue by yrose** [phon-ca/phon#193]
New syllabifier maximizes:

 - GV syllable as a rising diphthong
 - coda syllabification before onset syllabification
 
**Note:** It is possible that this syllabifier breaks other examples in the language. Could we introduce it in Phon as CMN-new or something, so we can test with it more in depth?

[cmn.txt](https://github.com/phon-ca/phon/files/7715699/cmn.txt)

**Comment by ghedlund** [comment]
Since this will have to be put up as a beta there's really no need to use a different name - they can just revert back to the previous version of the application to get the older version.
