### ISSUE TITLE
Phon 2.2.0b10 crashes on Mac OS 10.10.5

### ISSUE THREAD

**Issue by benjp** [phon-ca/phon#2]
the last beta crashes after startup on Mac OS 10.10.5. Is it a known issue?

**Comment by ghedlund** [comment]
Hello Benjamin,

Thanks for letting us know.  We have been using Phon on the newest 
version of macOS without issue, perhaps you could provide some more 
information.  When does the application crash?  Are any error messages 
displayed?

Cheers,

-Greg

**Comment by ghedlund** [comment]
P.S., We have newer downloads for the Phon beta now as well, you can 
find them at

https://github.com/phon-ca/phon/releases

-Greg

**Comment by benjp** [comment]
Hi - I can't help anymore as my wife requested to upgrade to Sierra to be able to work.
The app was appearing shortly and then was crashing. With Sierra on the same laptop, no issue.

**Comment by ghedlund** [comment]
Thanks for the report. I can confirm this is an issue with Yosemite.  I'm not sure why as I do not have access to a computer running that version of macOS.  As you mentioned, upgrading to Sierra seems to fix this problem.
