### ISSUE TITLE
Interface issue with segmentation window on low-resolution screen

### ISSUE THREAD

**Issue by yrose** [phon-ca/phon#212]
In its current form, the window that appears when we click "start segmentation" within Timeline is too long for computer with limited resolution. As a result, the user cannot see or click on the "start segmentation" button at the bottom of the window. 

A potential solution would be to think of a different way to display the instructions, maybe to the right of the parameters. I would not remove them, though: people find them very useful

**Comment by ghedlund** [comment]
Should be fixed in next beta
