### ISSUE TITLE
Tier editing and Anonymize functions in Participant information window seem broken

### ISSUE THREAD

**Issue by yrose** [phon-ca/phon#237]
The behaviours in this clip are from 3.5.0. Legacy version 3.4.3 was fine.

https://user-images.githubusercontent.com/15111886/204051242-912671f5-5ce9-47ba-ae00-340260562cfb.mov

**Comment by ghedlund** [comment]
New participant editor corrects this issue as well allows clearing of individual fields via a context menu visible by clicking the field label. Birthday and age have an additional menu item to calculate from the other if enough information is available.  The 'assign id from role' checkbox has been removed, this action can now be found in the context menu for the id field.
