### ISSUE TITLE
Word groups split into individual groups during roundtrip

### ISSUE THREAD

**Issue by yrose** [phon-ca/phon#238]
As per the screen shot (and with original session file attached). Shouldn't the roundtrip maintain the same word group structure?

[010822.txt](https://github.com/phon-ca/phon/files/10094933/010822.txt)
![Roundtrip behaviour](https://user-images.githubusercontent.com/15111886/204051632-71d34330-348e-40e8-872f-0146e50f2d5a.png)

**Comment by ghedlund** [comment]
It's because there is nothing in the IPA fields.  The behavior we decided when importing words from CHAT was to place them into individual groups.  If you had data in the IPA fields a group would have been created when exporting from CHAT to talkbank.

**Comment by yrose** [comment]
OK -- thanks for the swift reply!

On Nov 25, 2022, at 4:49 PM, Gregory Hedlund ***@***.******@***.***>> wrote:



It's because there is nothing in the IPA fields. The behavior we decided when importing words from CHAT was to place them into individual groups. If you had data in the IPA fields a group would have been created when exporting from CHAT to talkbank.
