### ISSUE TITLE
Turkish transliteration

### ISSUE THREAD

**Issue by yrose** [phon-ca/phon#30]
Attached:
* translit table 
* post-translit rules
* session (with txt extension) with examples in IPA Target

[TurkishTranslitTable.txt](https://github.com/phon-ca/phon/files/2506466/TurkishTranslitTable.txt)

[Turkish PostTranslit rules.txt](https://github.com/phon-ca/phon/files/2506467/Turkish.PostTranslit.rules.txt)

[Turkish IPATargets.txt](https://github.com/phon-ca/phon/files/2506468/Turkish.IPATargets.txt)

**Comment by yrose** [comment]
That makes full sense. In this context, you can base the four rules on the "following" vowel in the string, independent of syllable. So for example: 

k > c before {v, front}

**Comment by ghedlund** [comment]
Added in 3.0.2b1
