### ISSUE TITLE
Inverted character order involving ligatures in phonex queries

### ISSUE THREAD

**Issue by yrose** [phon-ca/phon#31]
In the session attached:

Search for t̠͡j in a Phones or Data Tiers query: no results returned
Search for {glide}:o, then t̠͡j is returned but in the reversed order: j͡t

[020006.txt](https://github.com/phon-ca/phon/files/2548371/020006.txt)

**Comment by yrose** [comment]
OK and OK. Hopefully the 'reversal' issue will disappear with the next beta!

**Comment by ghedlund** [comment]
Issue was an artifact with the 'previous_query_report' folder in the application data folder.  Deleting this folder fixed the issue.
