### ISSUE TITLE
Results highlighting in Session Editor after queries for multiple segments

### ISSUE THREAD

**Issue by yrose** [phon-ca/phon#32]
The highlighting of segments within the Session Editor only works for n-1 segments in a sequence. 

Example query: {c}:o+

If three segments are returned, only the first two are highlighted
If two segments are returned, only the first is highlighted
If one segment is returned, the highlight falls to the left of it

This is true for both IPA Target and IPA Actual tiers.

Attached file is slightly different than the one used for my report on the previous issue:

[020006.txt](https://github.com/phon-ca/phon/files/2548400/020006.txt)

**Comment by ghedlund** [comment]
Already taken care of ;) This was an issue introduced in the last beta.
