### ISSUE TITLE
3 maintenance tasks around diacritic 0x0353

### ISSUE THREAD

**Issue by yrose** [phon-ca/phon#38]
Add new feature to feature set: 
- feature: spirant
- shorthand: spi
- primary family: diacritic

Add feature spirant to 0x0353 (combining X below) 

Add 0x0353 to IPA Map, under 0x0320 in Diacritics section (it is currently in "Other Combined Diacritics)

**Comment by ghedlund** [comment]
Completed in Phon 3.0.4.
