### ISSUE TITLE
Changes to Ignore Diacritics

### ISSUE THREAD

**Issue by ghedlund** [phon-ca/phon#51]
Ignore diacritics currently includes tonal characters and in some instances this is not desirable.  There may be other situations where certain classes of diacritics should remain in the stripped version of the transcript.

Find a way to support these cases while not over-cluttering the UI.

**Comment by ghedlund** [comment]
Changes to implement:

 [] Change the ```IPATranscript.stripDiacritics()``` method so that tones are retained
 [] Create a new method ```IPATranscript.stripTones()```
 [] Add a new option to relevant reporting functions ```ignoreTones```

**Comment by yrose** [comment]
One very clear use case I just came across (concretely) is the need for an option whereby the "Distorted" diacritic effectively gives a "free pass" to an actual phone, i.e. treat that phone as identical to its target correspondent. For example, in the attached session, a PCC analysis with this option should return 75% accuracy. 

(This request is in line with one by Jon Preston about a year ago - I am not sure whether you developed methods to address this at the time.)

[Distortions.txt](https://github.com/phon-ca/phon/files/4026948/Distortions.txt)

**Comment by ghedlund** [comment]
Last comment may need to be moved to a new issue but closing this for now.
