### ISSUE TITLE
Add Orthography, IPA Target and IPA Actual (word-level) information to Consonants analysis data listings

### ISSUE THREAD

**Issue by yrose** [phon-ca/phon#54]
In the Consonants analysis, the listings should also incorporate, for each token, the words (in Orthography, IPA Target and IPA Actual) where these tokens are found

**Comment by ghedlund** [comment]
This can be achieved by adding 'Orthography' to the 'Add Aligned Words' field under Word Options - should this be made default?

**Comment by yrose** [comment]
Yes, please. It's the second time I have to address this issue, and both time I overlooked that obvious solution (duh). Having this as a default will alert users of the option in the first place. Thank you!
