### ISSUE TITLE
Word-level analysis of polysyllables

### ISSUE THREAD

**Issue by yrose** [phon-ca/phon#55]
For distortion analysis: distorted segments are identified through:

• 0x033e - The 'distorted' diacritic
• 0x032e - The Shriberg, Kent, McAllister, and Preston (2019) derhoticized diacritic,  
• 0x02e1- Lateral release diacritics 
• 0x032a - Dental diacritic

Recall: distortions aren't substitutions, so data analyzed as one should not be analyzed as the other.

**Comment by ghedlund** [comment]
Just to confirm - the base phone must be the same in IPA Target and Actual as well?

**Comment by yrose** [comment]
yes, that is correct! Other diacritic-based differences should be allowed in the IPA Actual (i.e. the ones listed here in addition to any other, e.g. length or creaky voicing).

**Comment by ghedlund** [comment]
Done. Also fixed the issue with the accounting of distortions.
