### ISSUE TITLE
Diacritics missing on Windows

### ISSUE THREAD

**Issue by ghedlund** [phon-ca/phon#57]
Diacritics 0x0321 & 0x0322 under the 'Diacritics' section do not render properly when using Charis SIL fonts on Windows.

**Comment by ghedlund** [comment]
According to the Charis SIL support page these two glyphs are not officially supported by the font.  As a result the java method Font.canDisplay(char) reports false for these two glyphs on windows.

Many other fonts, such as Arial, Times, etc. do have these diacritics but do not support the NE/SE arrows found in the tones section of our IPA Map.

**Comment by yrose** [comment]
Hi Greg,
Waiting on SIL may not be the best idea.

If these arrows are the only issue with the alternative fonts, I wouldn't object to removing them from our set.

See you soon!

Sent from my iPhone

On Sep 18, 2019, at 07:55, Gregory Hedlund <notifications@github.com<mailto:notifications@github.com>> wrote:


According to the Charis SIL support page these two glyphs are not officially supported by the font. As a result the java method Font.canDisplay(char) reports false for these two glyphs on windows.

Many other fonts, such as Arial, Times, etc. do have these diacritics but do not support the NE/SE arrows found in the tones section of our IPA Map.

-
