### ISSUE TITLE
Horizontal Scrolling in Speech Analysis window

### ISSUE THREAD

**Issue by nikowong** [phon-ca/phon#58]
I am using Phon 3.0.5 on macOS 10.14.6
I cannot do horizontal scroll on my mouse's scroll wheel (that I could do in Audacity). Can Phon add horizontal scroll support so that I could do scroll throw the window a lot faster and easier?

**Comment by ghedlund** [comment]
Thanks for your feedback.  I will investigate this during planned upgrades to this component.

**Comment by ghedlund** [comment]
Fixed in Phon 3.1
