### ISSUE TITLE
macosx & Java 12 - Issues with Combining Diacritics

### ISSUE THREAD

**Issue by ghedlund** [phon-ca/phon#60]
Starting with Java 12 any text field which contains combining diacritics has a blank box character added to the end of the text. The box is not replacing a character - seems to be a rendering issue.

**Comment by yrose** [comment]
Could this relate to the rendering issue we are facing when we use multiple combining diacritics? (I couldn't find a ticket about this...)

**Comment by ghedlund** [comment]
Seems to be an issue with property/jar load order when running things in eclipse.
