### ISSUE TITLE
Default Font not Recognized on Windows

### ISSUE THREAD

**Issue by michymorrow** [phon-ca/phon#65]
Downloaded fonts and can use them on other programs, but Phon is failing to find them. I receive this error message (see attached). When I reset preferences to default, it displays the correct font name; however, the preferences don't save and when I manually select a font the default fonts do not appear in the font list. I also tried to uninstall and reinstall Phon but that did not fix the issue. I am using Windows 10.
<img width="689" alt="error message fonts" src="https://user-images.githubusercontent.com/44653894/65480127-8fec8000-de4d-11e9-9a95-01182b1e60bc.PNG">

**Comment by ghedlund** [comment]
Thanks for reporting this issue.  We are re-evaluating our default font preferences for future versions of the application. A list of fonts which work well with IPA transcription on windows can be found here: https://www.phon.ucl.ac.uk/home/wells/ipa-unicode.htm.  Use can change the default fonts used for IPA transcription using the Preferences dialog in Phon. Unfortunately, the error message will persist for now if the JRE is unable to font the SIL fonts.

**Comment by ghedlund** [comment]
This warning will be removed in Phon 3.1.0.  Default fonts will be changed to use fonts available on installed OS.
