### ISSUE TITLE
Check sessions should incorporate word alignment check

### ISSUE THREAD

**Issue by yrose** [phon-ca/phon#66]
This function appears to be there, at least partially, in how Check evaluates phone alignment. A full check of this, including an account for zero-prefixed forms in Orthography (which have no correspondents in the IPA tiers) would help both our users (in general) and our workers (for the data roundtrip)

**Comment by ghedlund** [comment]
This will need to be implemented in the phon-praat-plugin as it relates to conversion into TalkBank.

**Comment by ghedlund** [comment]
CHAT checks (including cross-tier alignment) are now available in the Session Check dialog.
