### ISSUE TITLE
Crash when using Send back to calling program in Praat

### ISSUE THREAD

**Issue by yrose** [phon-ca/phon#67]
Opening TextGrids in Praat works in all versions. The send back function is stable using Phon 3.0.5 (stable) but crashes Phon 3.0.6-beta.4 as well as 3.1-alpha.3. The TextGrid file itself get updated (so no work is lost), but it seems like the updating in the Speech Analysis causes Phon to crash.

**Comment by ghedlund** [comment]
Closed as invalid?
