### ISSUE TITLE
PTC analysis

### ISSUE THREAD

**Issue by yrose** [phon-ca/phon#69]
To be integrated in general PPC analysis: 

Percentage of Tones correct

The way that our (upcoming) PCC/PVC will have options to ignore tone information, this new analysis would calculate percentage correct on aligned tones, without regard to accuracy on phones or non-tone diacritics.

**Comment by ghedlund** [comment]
We will need to create some test data for this.  I'm also thinking this will require its own query/analysis as the method for comparison is very different.
