### ISSUE TITLE
Phon 3.1.0-alpha: Not all aligned phones returned in Phones query

### ISSUE THREAD

**Issue by yrose** [phon-ca/phon#70]
Attached is the datafile (.txt extension) 

Basic Phones query with all default options and phonex (for IPA Target) ("look for nasal followed by a consonant):
{nasal}\c

* Aligned results not reported for certain records (records 5, 13, 18) (see screen shot)
* No error in log

[PN-MOmatlhaku.txt](https://github.com/phon-ca/phon/files/3745737/PN-MOmatlhaku.txt)

<img width="1178" alt="Screen Shot 2019-10-18 at 6 55 45 PM" src="https://user-images.githubusercontent.com/15111886/67129404-26a42680-f1d9-11e9-92aa-56ec8d0f60fb.png">

**Comment by yrose** [comment]
Issue in Alpha 4

**Comment by ghedlund** [comment]
Also related to problems created when implementing equals() and hashCode() for IPAElement.
