### ISSUE TITLE
3.1.0-alpha.4 - Error in Phones query on IPA Actual tier

### ISSUE THREAD

**Issue by yrose** [phon-ca/phon#71]
Using any phone-aligned dataset:

* Perform any query using the IPA *Actual* tier (as opposed to Target). Example queries:
{nasal}
\c

Phon reports an error (Phon.html attached (with txt extension)):

[phon.txt](https://github.com/phon-ca/phon/files/3745775/phon.txt)

[PPD 6yrs-3.txt](https://github.com/phon-ca/phon/files/3745762/PPD.6yrs-3.txt)

**Comment by ghedlund** [comment]
This is an issue related to the implementation of equals() and hashCode() of IPAElement and has been resolved.
