### ISSUE TITLE
Add Levenshtein distance calculation to compare blind transcriptions

### ISSUE THREAD

**Issue by yrose** [phon-ca/phon#79]
* Calculation for each session
* Within each session, one result/record (if not too hard: breakdown by word?)
* Assumes two (or more) blind transcriptions (not sure what to do if there are three, but I'd say number of calculations = number blind transcriptions minus 1; otherwise no result computable
* Option to include/ignore diacritics (incl. overrides, as per recent developments in Phon)

**Comment by ghedlund** [comment]
Completed in 3.2.0-beta.1
