### ISSUE TITLE
Comments at beginning of CHAT files don't appear in Phon sessions

### ISSUE THREAD

**Issue by ghedlund** [phon-ca/phon#8]
Comments at the beginning of CHAT sessions make it through the round trip and are present in the xml files for the Phon versions, but these are not visible when opening the session in Phon. Could they perhaps show up in the Project Manager window when the session is selected?

**Comment by yrose** [comment]
As this type of information is option, maybe we could have it visible as part of a 'More info' window, so as not to use an 'empty' interface space all the time?
